### ISSUE TITLE
Cannot setup pyDart2

### ISSUE THREAD

**Issue by lionellwolf** [Healthcare-Robotics/bodies-at-rest#7]
Hi, I was trying to set up Flex and Dart on my ubuntu.
I have built all other stuff but I failed to build pydart2.

When I try to run make, it fails to locate standard headerfiles, such as Vector, c++config.h, and features.h
(I have gcc/g++ 9 installed)

So I manually added the include_directories lines in CMakeList.txt.
but then, it failed again giving out the following error:

/usr/include/c++/9/bits/functexcept.h:42: Error: SYntax error in input(1).
make[2]: *** [CMakeFiles/pydart2_apu_swig_compilation.dir/build.make:64: CMakeFiles/_pydart2_api.dir/pydart_apiPYTHON.stamp] Error 1
make[2]: *** Deleting file 'CMakeFiles/_pydart2_api.dir/pydart2_apiPYTHON.stamp'
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/pydart2_api_swig_compilation.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

What should I do in this case?

**Comment by henryclever** [comment]
Hi,

Thanks for the inquiry.

Try using the following code to install pydart2:

```

########################INSTALL DART##########################
sudo apt-add-repository ppa:dartsim
sudo apt-get update
sudo apt-get install libdart6-all-dev
sudo apt-get install swig python-pip python-qt4 python-qt4-dev python-qt4-gl

cd git
git clone https://github.com/henryclever/pydart2.git
cd pydart2
sudo pip install numpy
sudo python setup.py build build_ext
sudo python setup.py develop

```

Some versions of Dart might not work. I think I manage to get my version of pydart2 working using Dart 6.6. 

Also, the weighing method for the capsulized body in this version of code could be better. It over-weights heavy bodies and under-weights light ones. I improved it in my latest work: [](https://github.com/Healthcare-Robotics/BodyPressure). The appendix provides details how how it is different. I may be able to dig up a code sample that you can drop in, let me know if you  want it .

-H

**Comment by lionellwolf** [comment]
Thank you for your response.

I used setup.py as you mentioned. However, attempting to import it in python gives me this error:

![Screenshot from 2021-10-19 09-48-03 (2)](https://user-images.githubusercontent.com/92708284/137825842-e5b70a0f-eb06-404d-b58d-a25339f23784.png)

I built Dart 6.6.0 from the source before installing pydart2

**Comment by henryclever** [comment]
OK - which version of Ubuntu are you using? 16.04? I just tried getting it to work on my fresh 18.04 copy and am not succeeding.  My computer running 16.04 has an os issue and I need to reinstall ubuntu to get it working again to I can reproduce your issue. I will work on this today.

If you have 16.04 -- Now that you have installed Dart 6.6 from source see if you can purge it and reinstall with apt-get to see if it works. Or just install with sudo apt-get on top of your current version. 

My FleX bindings are built for python2 and it seems this whole pipeline is constrained to ubuntu 16.04. Yikes. Would be great if someone would bring this up to date but I don't see myself doing it.

-Henry

**Comment by henryclever** [comment]
OK, i just got it working on a fresh install of 16.04 with the following:


#########################INSTALL DART############################\
`sudo apt-add-repository ppa:dartsim`\
`sudo apt-get update`\
`sudo apt-get upgrade`\
`sudo apt-get install libdart6-all-dev`\
`sudo apt-get install swig python-pip python-qt4 python-qt4-dev python-qt4-gl`
`sudo apt-get remove libdart*`\
`git clone git://github.com/dartsim/dart.git`\
`cd dart`\
`git checkout tags/v6.6.2`\
`mkdir build`\
`cd build`\
`cmake ..`\
`make -j4`\
`sudo make install`

Put the following at the end of your ~/.bashrc:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib:/usr/local/lib`


########################INSTALL PYDART2##########################\
`cd ~/git/`\
`git clone https://github.com/henryclever/pydart2.git`\
`cd pydart2`\
`sudo pip install numpy==1.16.6`\
`sudo pip2 install colorama six PyOpenGL`\
`sudo python setup.py build build_ext`\
`sudo python setup.py develop` \
Note that I haven't done this in a while with a fresh DART installation. It's possible that the current version of DART is incompatible with my pydart2 bindings. So in that case, you might have to downgrade to a previous version of DART. Hopefully you won't have to, though.

This link might be useful if you have trouble getting started: https://github.com/purdue-biorobotics/flappy/issues/2 


########################ACQUIRE PACKAGES#########################\
`sudo pip install scipy==0.16`\
`sudo pip install chumpy`\
`sudo pip install kiwisolver==1.1.0`\
`sudo pip install matplotlib==2.2.5`\
`sudo pip install opendr==0.76`\
`sudo pip install scikit-build`\
`sudo pip install packaging==20.0`\
`sudo pip install python-opencv==3.4.8.29`\
SMPL: http://smpl.is.tue.mpg.de/ \
SMPLIFY: http://smplify.is.tue.mpg.de/ \
For these latter two packages you will have to create an account with MPI, but it's not too tricky. Put their folders into the `~/git/` directory.

**Comment by henryclever** [comment]
Here is how I installed FleX. 

########################INSTALL FLEX##########################
`sudo apt-get install cmake`\
`sudo pip install pybind11`\
`cd git`\
`git clone https://github.gatech.edu/hclever3/FleX_pose_estimation.git` //you already have this from the compressed file
`cd FleX_pose_estimation`\
`git checkout master`\
NOW: comment out everything with a //*** in it in the demo/scenes.h file
`cd  ~/git/FleX_pose_estimation/demo/compiler/makelinux64`\
`make -j4`\
`cd ~/git/FleX_pose_estimation/extensions/compiler/makelinux64`\
`make -j4`\
NOW: uncomment everything with a //*** in it in the demo/scenes.h

**Comment by henryclever** [comment]
Also, 

I would appreciate it if you would provide some more details on the project you are working on with this, and who you are affiliated with! I'm just curious. But you don't have to post here - send me an email to henryclever@gmail.com.

-Henry
